hashgraph/MyHbarWallet

src/App.vue
src/components/ModalCustomerService.vue
src/components/ModalReportError.vue
src/main.css
src/main.ts
src/store/getters.ts
src/store/index.ts
src/store/modules/errors.ts
src/store/mutations.ts
src/support.ts
tests/unit/components/ModalReportError.spec.ts
yarn.lock

Add a method for reporting errors on uncaught exceptions

---

src/views/InterfaceSendTransfer.vue

remove BigNumber constructor from variable that was already a BigNumber

---

src/components/ModalRequestToCreateAccount.vue
src/views/InterfaceCreateAccount.vue
tests/unit/components/ModalRequestToCreateAccount.spec.ts

It was trying to create a private key from the entered public key.

Fix Public Key Validation in InterfaceCreateAccount

---

src/components/ModalAccessByPrivateKey.vue
src/components/TextInput.vue
src/views/InterfaceCreateAccount.vue
tests/unit/components/CustomerSupportLink.spec.ts
tests/unit/components/ExportKeystoreButton.spec.ts
tests/unit/components/FAQs.spec.ts
tests/unit/components/Footer.spec.ts
tests/unit/components/FooterTop.spec.ts
tests/unit/components/ModalAccessByHardware.spec.ts
tests/unit/components/ModalAccessByPhrase.spec.ts
tests/unit/components/ModalAccessByPrivateKey.spec.ts
tests/unit/components/ModalAccessBySoftware.spec.ts
tests/unit/components/ModalCreateByKeystore.spec.ts
tests/unit/components/ModalCreateWithSoftware.spec.ts
tests/unit/components/ModalCustomerService.spec.ts
tests/unit/components/ModalEnterAccountId.spec.ts
tests/unit/components/ModalExportGenerateKeystore.spec.ts
tests/unit/components/ModalKeystoreFilePassword.spec.ts
tests/unit/components/PasswordGenerator.spec.ts
tests/unit/components/TextInput.spec.ts
tests/unit/components/UnitConverter.spec.ts

Remove Spellcheck from Public Key on Account Creation

---

tests/e2e/assets/common/selectors.js
tests/e2e/specs/access/AccessAccountByKeystore.js
tests/e2e/specs/access/AccessAccountWithMnemonicPhrase.js
tests/e2e/specs/access/AccessAccountWithPrivateKey.js

fixes the e2e checks that were broken due to #73

Fix modal e2e checks

---

src/components/UploadFile.vue
yarn.lock

Chunk and upload files greater than 4kb

---

src/components/Modal.vue
src/components/ModalDownloadKeystore.vue
src/components/ModalEnterAccountId.vue
src/components/ModalFeeSummary.vue
src/components/ModalLogOut.vue
src/components/ModalRequestToCreateAccount.vue
src/components/ModalViewAccountId.vue
tests/unit/components/ModalEnterAccountId.spec.ts

This is mostly for buttons being too close together in the 400px-500px range, but also just makes style breaks more consistent

make mobile modal styling more consistent

---

src/components/UploadFile.vue

wont allow users to click if no file is present

added a disable to the file upload button

---

package.json
src/components/Modal.vue

branched from #138 
closes #59 
closes #138

Move electron dependency builder to its own command

---

src/components/Warning.vue
src/lang/en.json
tests/unit/components/ModalAccessByHardware.spec.ts
tests/unit/components/ModalAccessByPrivateKey.spec.ts
tests/unit/components/ModalAccessBySoftware.spec.ts
tests/unit/components/ModalCreateByKeystore.spec.ts
tests/unit/components/ModalCreateByPhrase.spec.ts
tests/unit/components/ModalCreateWithSoftware.spec.ts
tests/unit/components/ModalKeystoreFilePassword.spec.ts
tests/unit/components/Warning.spec.ts

…when they attempt to access a hardware wallet when they aren't on chrome

Added warning text for non-Chrome users

---

src/components/Modal.vue

Added a y translate to modals and sped up the animation slightly.
closes #92

fixing modal animations

---

src/components/Warning.vue
src/store/modules/errors.ts

also removed a `required` tag from a prop that doesn't need it

changed the user facing error to display the error message instead of stack trace

---

src/components/AccountTileButtons.vue
src/components/ModalAccessByHardware.vue
tests/unit/components/AccountTileButtons.spec.ts

should disable the button on browsers other than chrome

fixed the UA check for browser checking and disable the hardware access/create option

---

src/components/UploadZone.vue

just clear the input before selecting a file

can re-upload same file multiple times

---

src/components/ModalSuccess.vue
src/components/ModalUploadProgress.vue
src/views/InterfaceUploadFile.vue
tests/unit/components/ModalUploadProgress.spec.ts

use a separate success modal on file upload

---

src/App.vue
src/components/CustomerSupportLink.vue

I set the modals that would load on the initial page to be dynamically loaded instead. This brings the entry point size down to 448kb.
Related to #222

minor entry point optimizations

---

src/components/Header.vue
src/components/HeaderHamburgerButton.vue

hamburger button needed different styling on the interface, added a check to compensate. tested on galaxy s8 active and chrome mobile dev tools

fixed header styling on interface

---

vue.config.js

Configure Webpack  Performance Settings

---

src/views/InterfaceCreateAccount.vue

Fixing Form Validation for the `initial balance` on interfaceCreateAccount 

---

src/router.ts
src/store.ts
src/store/modules/errors.ts
src/store/modules/wallet.ts
src/wallets/Wallet.ts
src/wallets/hardware/LedgerNanoS.ts
src/wallets/software/SoftwareWallet.ts

**Note that this is branched off of #272** 
This PR cleans up most of the linting warnings we were getting.

Clean Up Lint Warnings

---

src/components/Footer.vue
src/lang/en.json
tests/unit/components/Footer.spec.ts

added a link to CoinGecko's website in the footer.

added CoinGecko link and disclosure to footer

---

src/components/PasswordGenerator.vue
src/lang/en.json
tests/unit/components/ModalCreateByKeystore.spec.ts
tests/unit/components/ModalExportGenerateKeystore.spec.ts

added textInput error on mismatched paswords

---

src/views/AccessMyAccount.vue
tests/unit/components/Footer.spec.ts

- Modifies verify account transaction to include no recipient

Ledger Review

---

src/views/InterfaceSendTransfer.vue

remove `entire balance` option from send transfer

---

src/components/HeaderHamburgerMenu.vue
tests/unit/components/Header.spec.ts
tests/unit/components/HeaderHamburgerMenu.spec.ts

Fix logout on mobile menu

---

src/components/Header.vue
tests/unit/components/Header.spec.ts

Before, Logging out by navigating home with the MHW logo wouldn't properly close the mobile menu. Now it does.

fix menu close error on logout

---

src/components/BalanceCard.vue
src/components/ModalPurchaseHbar.vue
src/lang/en.json
src/store.ts

Still need production key and a way to obscure it is supposed to be secret

WIP - add option to purchase hbar through Carbon

---

src/components/ModalAccessByPhrase.vue
src/components/ModalCreateByPhrase.vue
src/components/OptionalPasswordInput.vue
src/views/AccessMyAccount.vue
tests/unit/components/ModalCreateByPhrase.spec.ts
tests/unit/components/OptionalPasswordInput.spec.ts

This enables users to create and access a accounts using a password protected mnemonic phrase.
closes #128

Support Mnemonic Phrase passwords

---

src/components/PasswordGenerator.vue

https://github.com/hashgraph/MyHbarWallet/issues/321

Fix PasswordGenerator error handling for mismatch

---

src/components/Modal.vue
src/components/ModalLogOut.vue

- Fixes ModalForgotToLogout's awkward top heavy layout
- Fixes assorted slight overflow issues in modals at the right of screens

Adjust mobile modal style

---

package.json
public/site.webmanifest
src/index.html
vue.config.js
yarn.lock

added workbox support to generate a service worker.

Turn MHW into a PWA

---

src/components/Modal.vue

vh --> % on internal containers

fix long-modals problem

---

public/site.webmanifest

adjust pwa settings 

---

src/components/ModalUploadProgress.vue
src/views/InterfaceUploadFile.vue
tests/unit/components/ModalUploadProgress.spec.ts

chunking size was a touch too large, causing transaction oversize error

fix chunking size, implement retry, less jarring style for modals

---

src/components/MnemonicInput.vue
src/components/ModalPurchaseHbar.vue
src/components/ModalUploadProgress.vue
src/components/OptionalMemoField.vue
src/components/OptionalPasswordInput.vue
src/components/OptionalPasswordWithConfirm.vue

Also, run yarn lint
Signed-off-by: Daniel Akhterov <daniel@launchbadge.com>

Reset memo when `OptionalMemoField` is hiden

---

src/service/clipboard.ts
src/ui/components/ModalMessageSigned.vue
src/ui/components/ModalRequestToCreateAccount.vue
src/ui/components/ModalViewAccountId.vue
src/ui/components/ModalViewKeys.vue
src/ui/components/TextInput.vue
src/ui/views/InterfaceCreateAccount.vue
src/ui/views/InterfaceUploadFile.vue
tests/unit/views/InterfaceCreateAccount.spec.ts
tests/unit/views/InterfaceUploadFile.spec.ts
yarn.lock

- Aims to fix copy functionality for browsers that don't have navigator.clipboard
- refactors writeToClipboard to take a Vue | Element and extract text

Fallback clipboard handling

---

src/ui/components/ModalAccessByPrivateKey.vue
tests/e2e/specs/access.spec.ts

Allow combined private+public keys in ModalAccessByPrivateKey

---

src/components/interface/Assets.vue

Sorts tokens by balance in assets component

feat: sort tokens on assets page descending balance

---

src/components/base/TextInput.vue
src/components/interface/CustomerSupportModal.vue

Added text input limitations to Customer Support Modal. 
Added text input counter to description in Customer Support Modal
Made text input counters denominator dynamic, matching maxLength
Fixes #
N/A
**Notes for reviewer**:
N/A
**Checklist**

Added text input limitations to customer support modal

---

src/components/base/ReloadPrompt.vue
src/components/interface/LogoutModal.vue

- Fixes ReloadPrompt layout
- Fixes LogoutModal layout

fix: prompt layouts

---

locales/en.json
src/components/base/HbarInput.vue
src/components/base/TextInput.vue
src/components/interface/AssetInput.vue
src/components/interface/Layout.vue
src/components/interface/MainView.vue
src/components/interface/OptionalHbarInput.vue
src/pages/interface/Send.vue

Signed-off-by: Danielle Smith <danielle.smith@launchbadge.com>
-- Made min height of Layout the screen width -- in some cases (such as the "tools" component, the layout will not extend the full screen height and would result in empty space, needed to be fixed.

Fixed dark mode bug in Layout.

---

src/domain/CreateOptions.ts
src/pages/create/Create.vue
src/pages/create/Software.vue
src/router.ts

Signed-off-by: Chris Campbell <chris@launchbadge.com>
- Adds route for create with ledger
- Reworks create options available

feat: create options expanded

---

package.json
src/pages/access/Account.vue
src/pages/create/PrivateKey.vue
src/pages/create/Software.vue
src/pages/interface/Keys.vue

Signed-off-by: Chris Campbell <chris@launchbadge.com>
- Adds Create by Private Key route

feat: create by private key

---

locales/en.json
src/hooks/platform.ts
src/pages/access/Ledger.vue

Signed-off-by: Chris Campbell <chris@launchbadge.com>
- Checks WebUSB support before attempting to continue with ledger access

fix: check webusb support on ledger access

---

src/pages/interface/Send.vue

-- Fixed 2 bugs:
-- Endless IP sending modal
-- Error in console

Bug fix (2)

---

package.json
pnpm-lock.yaml
src/domain/wallet/hardware-ledger.ts

- Use BIP32 path, to more closely match ongoing ledger implementation

Bip32 path

---

src/pages/access/Account.vue
tests/cypress/integration/create/Mnemonic.spec.ts

E2E test for create mnemonic :)

Add mnemonic create e2e test

---

package.json
pnpm-lock.yaml
tests/cypress/integration/create/MnemonicPassword.spec.ts

Signed-off-by: Jack Ta <jack.th.ta@gmail.com>
- E2E test for creating wallet with mnemonic phrase and password
**Notes for reviewer**:
- I installed a password generator to simulate different users inputting different passwords, but if it's unneeded, I can remove it and have a const string in its place

Add create mnemonic w/ password e2e test

---

src/App.vue
src/components/interface/Nav.vue
src/pages/interface/Home.vue
src/pages/interface/Tools.vue
src/store.ts
tests/cypress/integration/wallet/Associate.spec.ts
tests/cypress/support/commands.ts
vite.config.js

Signed-off-by: Chris Campbell <chris@launchbadge.com>
- Adds a cypress login command

feat: Cypress login command

---

src/components/interface/Nav.vue

-- History navlink will not appear on Testnet or Previewnet

History navlink will not appear on Previewnet

---

locales/en.json
src/components/base/KeyInput.vue
src/components/base/TextInput.vue
src/pages/create/PrivateKey.vue

-- Updated canCopy and disabled/readOnly styles in KeyInput and TextInput components

canCopy and disabled/readOnly style updates

---

locales/en.json
src/pages/create/PrivateKey.vue
src/pages/interface/CreateAccount.vue
src/pages/interface/Send.vue
src/pages/interface/UploadFile.vue
src/services/impl/hedera/client/create-account.ts
src/services/impl/hedera/client/download-file.ts
src/services/impl/hedera/client/index.ts
src/services/impl/hedera/client/upload-file.ts
tests/cypress/integration/create/Mnemonic.spec.ts
tests/cypress/integration/create/PrivateKey.spec.ts

-- Replaced most SDK imports with dynamic imports (excluding Send and Cypress tests), mostly newer tools affected

Replace SDK imports with dynamic imports

---

locales/en.json
src/pages/interface/AssociateToken.vue
src/pages/interface/CreateAccount.vue
tests/cypress/integration/wallet/Associate.spec.ts
tests/cypress/support/commands.ts

This PR modifies
cypress: associate.spec
cypress: commands 
en.json
AssociateToken.vue
in order to support ...
* Add alerts for success and failure events on associate
* Add cypress testing for associate token
**Notes for reviewer**:
(\____/)
( ͡ ͡° ͜ ʖ ͡ ͡°)
\╭☞ \╭☞  Why did I stay up all night doing this? This was a mistake. 
**Checklist**

Associate token

---

src/components/base/OptionalPasswordInput.vue
src/components/interface/OptionalHbarInput.vue
src/components/interface/OptionalMemo.vue
src/pages/create/Mnemonic.vue
src/pages/interface/Send.vue

-- Fixed 'drop down' on optional components

"Drop down" fix

---

src/components/base/Button.vue
src/components/base/ReloadPrompt.vue

-- Minor appearance changes to modal to make more consistent with site colors

RefreshPrompt

---

src/components/interface/KabutoLink.vue

-- Fixed link to go to user's account instead of home page
-- Changed cursor to pointer on hover

KabutoFix: Fixed link

---

locales/en.json
src/components/base/KeyInput.vue
src/pages/interface/Keys.vue

-- Added optional prop to KeyInput component to pass in whether key is public or private, and adjust accordingly (default is private == true)

Issue #539: KeyInput Button Fix

---

locales/en.json
src/components/interface/TransactionFilterButton.vue
src/components/interface/Transactions.vue
src/components/interface/UploadZone.vue
src/domain/CryptoTransfer.ts
src/pages/interface/History.vue
src/services/hedera.ts
src/services/impl/hedera/client/get-account-records.ts
src/services/impl/hedera/client/index.ts
src/store.ts

-- Resolved issues with Kabuto V2 API updates
-- Rebuilt previous refactor
***NOTE FOR REVIEWER***
Token details are part of another branch that is likely outdated, will need to update the token detail branch and submit separate PR.

Refactor: History

---

locales/en.json
src/components/interface/ConfirmationModal.vue
src/components/interface/LogoutModal.vue
src/components/interface/UploadZone.vue

-- Improved appearance of confirmation and logout modals.

ConfirmationModal

---

src/services/impl/hedera/client/get-account-records.ts
src/store.ts

-- Moved serverAddress from store to get-account-records

History: Moved serverAddress from store to get-account-records

---

src/components/interface/AddTransferModal.vue
src/components/interface/AssetInput.vue
src/components/interface/TransferConfirmationModal.vue
src/components/interface/TransferForm.vue
src/components/interface/TransferItem.vue
src/pages/interface/Send.vue
src/services/impl/hedera/client/get-account-records.ts
src/services/impl/hedera/client/transfer.ts

-- Fixed 'fractional token' issue
-- Fixed input issue with leading 0s in the decimal preventing smaller token transfers
-- Removed token info queries to prevent invisible transactions

FractionTokens

---

src/components/access/LedgerInfo.vue
src/components/marketing/Faqs.vue

Signed-off-by: Jack Ta <jack.th.ta@gmail.com>
- Create|Access > Hardware > Ledger > "Don't have an Account?" guide link
- Home > FAQs > "If I send you my public key, will you make me an account?" > guide link
- The two above guide links are outdated; this PR will fix that.

refactor: update 'create hedera acc using ledger' guide link

---

.github/CODEOWNERS

Per #597 added a CODEOWNERS file
**Related issue(s)**:
Fixes #597

ci: Q3 Audit Tasks -- Added CODEOWNERS

---

.github/CODEOWNERS

Update devops-ci to be platform-ci
Fixes #607

chore: Update codeowners for platform-ci team
